### ISSUE TITLE
Feature request / suggestion   accessing Grub menu

### ISSUE THREAD

**Issue by BKButter** [Microsoft/azserialconsole#30]
It is great to have a serial console, this option allowed me to recover a with Red Hat server with selinux issues.

The only problem I encountered, is to halt the startup to enter the grub boot menu.
If you have the option to restart the VM you are fine.  
0)	Option serial console
1)	Restart VM
2)	Go back to the Serial console. when connection breaks “enter button” and then keep on tapping the space bar.

I had only the option, to start the VM and this did not give me the time needed to halt the startup and enter the Grub menu, the time I got a serial console screen the server is already past the grub menu.
Workaround.
0)	Startup the VM server
1)	Open a serial console menu
2)	Use Powershell to initiate reboot from the VM server.
Restart-AzureRmVM -Name “name” -ResourceGroupName “resourcegroup”

3)	Go back to the Serial console. when the connection breaks “enter button” and then keep on tapping the space bar.

A nice feature to have stop start and reboot option in the serial console menu, and have automatic reconnect back to the serial console.

**Comment by amitchat** [comment]
Thanks for using the serial console and providing some great feedback @BKButter. We did notice the issues around reboot and re-connection in the scenario you have mentioned and are planning to add the capability to auto reconnect so that you don't have to reestablish the connection manually by going back to the Serial Console option (or) pressing Enter. This should make it easier to get to GRUB immediately once the VM is up during a "Restart VM".

At this point we haven't considered adding a VM reboot option in the serial console UI, but it does sound like a good idea and we will consider it in our roadmap. As a workaround, as you have suggested, you can use the CLI (or) open a new portal browser window (or) use the Azure CloudShell to initiate the reboot while keeping the serial console window open in the browser.

**Comment by amitchat** [comment]
Closing as the auto-reconnect feature has been implemented and deployed.
