### ISSUE TITLE
full RDP-style console access to the Windows GUI

### ISSUE THREAD

**Issue by omegagx** [microsoft/azserialconsole#32]
I see there is a command line for Windows but not full RDP-style access to the console GUI on Windows. Also, we need the ability to mount ISOs and to boot off them in Windows. When would those features be added?

**Comment by asinn826** [comment]
Hi @omegagx - thanks for the good suggestions, we have these in our roadmap.

**Comment by DavidG2604** [comment]
Push - please up the priority of this on your roadmap. The serial console is a great thing for linux machines but it's not what we expect to service and troubleshoot windows machines. Also it seems to be such a basic feature that every hypervizor had in the last 20 years. Full KVM console access and mapping of ISOs to virtual cd drives is really helpful if you ever have to troubleshoot a windows VM not properly booting or something.

**Comment by oobedan** [comment]
Really need a proper GUI (not RDP) console in Azure. The amount of times I've locked myself out of a VM or Windows updates that can kill RDP, really stops some use cases for mission critical IaaS in Azure for me.

**Comment by Alsmk2** [comment]
... and here we are four years later without a proper KVM console.

How long is this roadmap? To the moon and back?

I have a VM which won't work with any network interface, so RDP and Bastion are both out. The command to enable the serial console from the portal doesn't work. I've had to mount the OS disk to a separate VM, to enable EMS. That didn't work. Nice trick was to use the RunOnce reg SZ keys with auto login to try and enable EMS. That partially worked... I can now get to the boot loader menu, but past that EMS fails. Result? A business critical VM has been offline all day and is currently unrecoverable.

Let's also give an honorable mention to the the NLA annoyance with DC's aren't available. 

In vSphere, I right-click and select Open Console. Job done. 

Sort it out Microsoft.

**Comment by oobedan** [comment]
@Alsmk2 install the SCCM/ConfigMgr client, sort of gives you a console over IP outside of RDP reliance. But MS should really have  console by now.

**Comment by DavidG2604** [comment]
I made myself an emergency VNC setup with inactive VNC servers installed on every machine that could be launched from command line or remote-mmc, and also activated the boot menu so i can boot into safe mode from the serial console and even whitelistet the VNC server as a service startable under safe mode.

However it is still requires the IP access for vnc and if remote-mmc etc. fails, the cmd session inside the serial console working for launching that VNC server.

It's not a great solution but already came to good use in the past.
However I should not have to hand-craft a console access solution just because I am on Azure. Especially not when I am on Azure.

The first day I was introduced to Azure and saw this, I was stunned on the lack of feature here. Things that seemed as natural as the blue sky were missing. I wanted my vSphere 5 back.

Fix it Microsoft. This is utter lazyness.

**Comment by omegagx** [comment]
@asinn826 - do you have any updates on the roadmap?

> Hi @omegagx - thanks for the good suggestions, we have these in our roadmap.

**Comment by hechter80** [comment]
Thank you Microsoft for nothing!! First comment from 2018 and still we have this f* serial console like 1980. Every small Server Hoster has a KVM Console, but M$ can´t!

**Comment by matti** [comment]
lol

**Comment by No1234DDgg** [comment]
Danke Microsoft für garnichts. wirklich vielen Dank!!!! 
Greetings from Germany 2024 btw.

**Comment by mbifeld** [comment]
Apologies this request has gone on so long without any updates.  As one might have guessed by no updates for 6 years, GUI access via Serial Console is not currently on our roadmap.  Azure Serial Console only provides serial console access which is limited to text only.  Closing as not planned.

**Comment by omegagx** [comment]
@mbifeld 
![image](https://github.com/microsoft/azserialconsole/assets/19207488/cc482b2d-f362-4e61-89f5-661405eb527b)
As you can see, it was on the roadmap in 2018. When was this removed from the roadmap?

**Comment by mbifeld** [comment]
It was removed from the roadmap earlier this year as only initial scoping was worked on the last 6 years.  It kept getting pushed down the line, and due to the amount of work required and a recent reprioritization of internal security improvements, we have decided to formally remove this from the roadmap as we realize it will be at least another couple years until it’s considered again, and we shouldn’t have you all waiting in the unknown like you have been.  Hopefully one day this can be reevaluated again, but just want to be frank that it won’t be anytime soon.
