### ISSUE TITLE
No scroll on windows console

### ISSUE THREAD

**Issue by guillemsola** [Microsoft/azserialconsole#43]
I found really difficult to accomplish some tasks without having access to more than what just fits on the screen,

I've been trying it with windows CMD and PowerShell sessions.

One can use alternatives like `ls | more` but really slows things.

BTW keep going that way!!!

**Comment by asinn826** [comment]
@guillemsola Thanks for the feedback - with the windows SAC, the mechanism is very low level and there is actually no scrolling supported. For historical reasons only an 80x25 text mode screen was supported, so this is what we have to work with today.

**Comment by dikadali** [comment]
It's same issue with Linux serial console as well. it would be very helpful if it is fixed.

SAC cmd console is not utilizing screen size and unable to scroll through old cmd history. 
OS: windows
![image](https://user-images.githubusercontent.com/45972925/50807335-f4979700-131f-11e9-9619-de96baceef31.png)

**Comment by asinn826** [comment]
Hey @dikadali - could you share some details on what you were doing on the Linux end? AFAIK there is the ability to scroll up for Linux VMs, but this doesn't work on Windows. Your screenshot looks like a SAC prompt, which would be on a Windows VM.

Interestingly, part of the reason is historical and part is design - Linux has always seen TTY as a legitimate means of interacting with the OS, whereas Windows has always assumed that the PC is tied to an actual monitor. So Linux consoles are treated as a stream of bytes, whereas Windows consoles are treated as a rectangle of text. And since serial isn't native for Windows, we get this strange lack of upwards scroll that you are noticing :) If this behavior changes in future Windows releases, you will notice them when their images are available in Azure.
