### ISSUE TITLE
Implement readline/editline keybindings (e.g. ^W)

### ISSUE THREAD

**Issue by LukeCarrier** [microsoft/azserialconsole#68]
At present, regardless of whether or not the serial console input is focused, pressing `^W` (remove word) will result in the tab being closed. This is frustrating when you're trying to restore network connectivity from the serial console in a pinch as the keybinding is burned into muscle memory.

Tested in Firefox 68.0.4.

**Comment by asinn826** [comment]
@LukeCarrier I liked the original title better :). We hear your pain, this is something we'll pick up. Thanks for the feedback!

**Comment by asinn826** [comment]
I realize that this ask is still outstanding, and since I also feel strongly about this, I'll leave a quick comment here that due to a bunch of high pri behind-the-scenes work we're doing right now, this bug has been deprioritized. We did an initial investigation into this and the result of that was that this bug was going to be harder to fix than we initially thought. Deprioritizing this was a tough decision to make but I'll be pushing for this bug to get fixed when we get a chance.

**Comment by asinn826** [comment]
Update - now you won't be able to shoot yourself in the foot with ^W:
![image](https://user-images.githubusercontent.com/6633402/81749960-7aba7500-9461-11ea-9a8e-3e0990d08926.png)

Note that you won't be able to remove word (that was trickier) but you won't be able to accidentally close the tab. This will work for any active serial connection (^W on loading screen will still) close tab.

**Comment by LukeCarrier** [comment]
@asinn826, you're a hero.
