### ISSUE TITLE
(╯°□°）╯︵ ┻━┻

### ISSUE THREAD

**Issue by LukeCarrier** [microsoft/azserialconsole#84]
```
For more information on the Azure Serial Console, see <https://aka.ms/serialconsolelinux>.
Preparing console connection to salt-master0   ■ □ □
The serial console connection to the VM encountered an error: ''
 (ConnectionFailure) - A connection could not be established. Please restart Cloud Shell to try again.
```

**Comment by LukeCarrier** [comment]
It's working now. Yet another transient failure Microsoft won't acknowledge in the [Azure status history](https://status.azure.com/en-gb/status/history/).

**Comment by asinn826** [comment]
😢 We have been seeing more of these pop up in recent weeks. I'll share a bit more context (I hope I'm allowed to do so) - in recent weeks there has been a *big* push to clean up a lot of backend pieces with Serial Console, Cloud Shell, and the rest of Azure. We are in the midst of all this work, so all of the mucking around we are doing is having unintended side effects, ugh! We're aware of it within the team and while I can't commit a date this will be fixed by at this point, I'm pushing for attention to be put on this one.

**Comment by LukeCarrier** [comment]
Thanks Alfred.

If possible, it might be worth changing the error message to make it clear
that this is a transient failure related to a known service problem. This
service is an important lifeline when using services Iike Azure Disk
Encryption where it's otherwise difficult to monitor progress.

One of the biggest frustrations for me with the Azure platform as a whole
is that error reporting often leaves me in the dark. '' isn't much to go on
😉

**Comment by asinn826** [comment]
Agreed completely, and thanks for the feedback Luke! 

We have actually invested a bit of work in the past couple months to come up with a set of friendlier errors to some common error cases that we notice in our telemetry (the boot diagnostics one comes to mind, although you probably haven't seen it since it comes up for first-time users who haven't configured their VM for boot diagnostics). But there's always more error cases we can capture and transient ones like this should definitely be called out so that you as a user know to just try again. Ideally this wouldn't even happen...

Your use case is interesting. Out of curiosity - are you using serial console to monitor encryption status of your VM since SSH access isn't possible while a disk is being encrypted?

**Comment by LukeCarrier** [comment]
That's awesome! I realise it's difficult to communicate changes like this at a level of granularity that works for everyone, but I'd definitely be interested in a changelog for the service.

Yep -- for Linux systems the VM enters a fairly locked down state while it formats the root partition and the only way to monitor progress is to watch the console logs. This console has been a _lifesaver_ for us for the last couple of weeks -- we've hit a lot of snags rolling out disk encryption. I've documented all of them and will definitely be raising issues against the `AzureDiskEncryptionForLinux` extension.

**Comment by asinn826** [comment]
Let me think some more about the changelog piece - not sure if there's a good place for it within the high level Azure status sites, but perhaps somewhere else...

We've also begun rolling out an update which should help resolve the error you originally saw, so that'll come out over the next several days. 

If you're not getting much traction with your feedback on ADE, feel free to share with me as well and I'm happy to bring that feedback to the ADE team. We're spending some time looking at the overall end-to-end Linux on Azure experience and one topic of interest in that space recently has been ADE.

**Comment by mbifeld** [comment]
Closing this as the original error is fixed.  If you are still interested in a change log for Serial Console, please file a new issue so we can triage appropriately.  Thanks!
